name: halliq
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  nb_utils: ^5.0.8-beta.2

  # STATE MANAGEMENT
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  url_launcher: ^6.1.14

  # Fonts and Icons
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.5.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  
  fonts:
  - family: BalooBhaijaan2
    fonts:
     - asset: assets/fonts/BalooBhaijaan2-Regular.ttf
     - asset: assets/fonts/BalooBhaijaan2-SemiBold.ttf
       weight: 600
